inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect # default

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - fn
    # default allowed names
    - io
    - id
    - to
    - by
    - on
    - in
    - at
    - ip
    - db
